### ISSUE TITLE
giving error after running main.py

### ISSUE THREAD

**Issue by dhir4j** [Panc4kes/chess.com-bot#20] opened 2022-03-06 18:58 UTC
C:\Users\kapse\Downloads\chess\chess.com-bot-main\src>python main.py
Traceback (most recent call last):
  File "C:\Users\kapse\Downloads\chess\chess.com-bot-main\src\main.py", line 5, in <module>
    from pywinauto import application
  File "C:\Users\kapse\AppData\Roaming\Python\Python310\site-packages\pywinauto\__init__.py", line 89, in <module>
    from . import findwindows
  File "C:\Users\kapse\AppData\Roaming\Python\Python310\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "C:\Users\kapse\AppData\Roaming\Python\Python310\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "C:\Users\kapse\AppData\Roaming\Python\Python310\site-packages\pywinauto\controls\uiawrapper.py", line 47, in <module>
    from ..uia_defines import IUIA
  File "C:\Users\kapse\AppData\Roaming\Python\Python310\site-packages\pywinauto\uia_defines.py", line 181, in <module>
    pattern_ids = _build_pattern_ids_dic()
  File "C:\Users\kapse\AppData\Roaming\Python\Python310\site-packages\pywinauto\uia_defines.py", line 169, in _build_pattern_ids_dic
    if hasattr(IUIA().ui_automation_client, cls_name):
  File "C:\Users\kapse\AppData\Roaming\Python\Python310\site-packages\pywinauto\uia_defines.py", line 50, in __call__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "C:\Users\kapse\AppData\Roaming\Python\Python310\site-packages\pywinauto\uia_defines.py", line 63, in __init__
    self.ui_automation_client.CUIAutomation().IPersist_GetClassID(),
AttributeError: module 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation'

![Screenshot (87)](https://user-images.githubusercontent.com/77230041/156937963-09125f27-88cf-4a3d-a858-fd04b6b68e72.png)

cmd logs

**Comment by jsun1590** [comment] 2022-03-07 03:18
Hi, thank you for reporting this issue. I will review and get back to you.👍

**Comment by jsun1590** [comment] 2022-03-18 13:15
Hi, I was able to run this locally on my machine fine with Python 3.10. Googling this error, it looks to be related to the `comtypes` sub module. Could you please install `comtypes` again via `pip3 install comtypes` or `pip install comtypes`.

As the issue is not with this script, I will be closing this issue.

Thank you!

**Closed as completed** 2022-03-18 13:16 UTC
Labels: bug
